/* PRIMARY Keys */
ALTER TABLE Users ADD CONSTRAINT user_pk PRIMARY KEY (userID);
ALTER TABLE Posts ADD CONSTRAINT post_pk PRIMARY KEY (postID);
ALTER TABLE Comments ADD CONSTRAINT comment_pk PRIMARY KEY (commentID);
ALTER TABLE Replies ADD CONSTRAINT reply_pk PRIMARY KEY (replyID);
ALTER TABLE Sections ADD CONSTRAINT section_pk PRIMARY KEY (sectionID);
ALTER TABLE userRoles ADD CONSTRAINT userRole_pk PRIMARY KEY (roleID);
ALTER TABLE likes ADD CONSTRAINT like_pk PRIMARY KEY (commentID, userID);
ALTER TABLE votes ADD CONSTRAINT vote_pk PRIMARY KEY (postID, userID);

/* Foreign Keys */
ALTER TABLE Posts ADD CONSTRAINT Posts_userID_FK FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Posts ADD CONSTRAINT Posts_sectionID_FK FOREIGN KEY (sectionID) REFERENCES Sections(sectionID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Comments ADD CONSTRAINT Comments_postID_FK FOREIGN KEY (postID) REFERENCES Posts(postID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Comments ADD CONSTRAINT Comments_userID_FK FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Replies ADD CONSTRAINT Replies_commentID_FK FOREIGN KEY (commentID) REFERENCES Comments(commentID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Replies ADD CONSTRAINT Replies_userID_FK FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE userRoles ADD CONSTRAINT userRoles_userID_FK FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE likes ADD CONSTRAINT likes_commentID_FK FOREIGN KEY (commentID) REFERENCES Comments(commentID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE likes ADD CONSTRAINT likes_userID_FK FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE votes ADD CONSTRAINT votes_postID_FK FOREIGN KEY (postID) REFERENCES Posts(postID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE votes ADD CONSTRAINT votes_userID_FK FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE;

/* E-post format */
ALTER TABLE Users ADD CONSTRAINT email_format CHECK (email LIKE '%_@__%.%');

/* Usernames är unika */
ALTER TABLE Users ADD UNIQUE (username);