DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Posts CASCADE;
DROP TABLE IF EXISTS Comments CASCADE;
DROP TABLE IF EXISTS Replies CASCADE;
DROP TABLE IF EXISTS Sections CASCADE;
DROP TABLE IF EXISTS userRoles CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS votes CASCADE;








